<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6oxeNkd\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6oxeNkd/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container6oxeNkd.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container6oxeNkd\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container6oxeNkd\appAppKernelProdContainer([
    'container.build_hash' => '6oxeNkd',
    'container.build_id' => '947bf501',
    'container.build_time' => 1677674540,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6oxeNkd');
