<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEUoXJhU\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEUoXJhU/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerEUoXJhU.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerEUoXJhU\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerEUoXJhU\appAppKernelProdContainer([
    'container.build_hash' => 'EUoXJhU',
    'container.build_id' => 'f93b91a5',
    'container.build_time' => 1676537870,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEUoXJhU');
